### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by zlepper** [dariogriffo/Rebus.OpenTelemetry#1]
Hey :)

I saw that you have this project, and wondered if you plan on continuing it, or if we are allowed to use the code directly, and maintain a fork ourselves? 

We are currently looking at using OpenTelemetry with Rebus, and I thought it would be easier to build of something where you seem to have done most of the hard work, rather than figuring everything out from scratch.

**Comment by dariogriffo** [comment]
Absolutely, go for it, I started this during lockdown, but never finished shaping it, it will be good to talk to @mookid8000 and coordinate how he prefers this to happen, as a contribution, or transfering the ownership of the repo, or just start one from scratch

**Comment by zlepper** [comment]
My plan was to just "borrow" your code, set it up in our internal mono-repo, develop it until everything works, and then go poke @mookid8000 if he would like to back in the Rebus org.

**Comment by dariogriffo** [comment]
Also, as side note, I based this code on [this](https://github.com/jbogard/NServiceBus.Extensions.Diagnostics.OpenTelemetry) from @jbogard after reading [this](https://twitter.com/jbogard/status/1243208651575345152)

**Comment by dariogriffo** [comment]
> My plan was to just "borrow" your code, set it up in our internal mono-repo, develop it until everything works, and then go poke @mookid8000 if he would like to back in the Rebus org.

If I have to be honest, I would like this to be created from scratch under the rebus-org with you contributing and allowing more people to make part of it, but is not up to me :)

**Comment by zlepper** [comment]
> > My plan was to just "borrow" your code, set it up in our internal mono-repo, develop it until everything works, and then go poke @mookid8000 if he would like to back in the Rebus org.
> 
> If I have to be honest, I would like this to be created from scratch under the rebus-org with you contributing and allowing more people to make part of it, but is not up to me :)

I certainly get that, but with what you already have here, i doubt we are talking multiple weeks of work. So it's probably a day or two until i have it working completely as i want, and then it can go under the Rebus org. 

It's just easier to test and everything when you have your normals tools and all that available :D

**Comment by mookid8000** [comment]
No matter how it gets there, I would be absolutely thrilled if rebus-org could incorporate an Rebus.OpenTelemetry repo at some point.

@zlepper if you build on @dariogriffo 's work somehow, maybe it makes sense to fork this repo and continue off of it? Then his commits will be there as a testament to groundwork made by him.

In any case, I'd be happy to accept the repo into rebus-org when it's ready for action 🤠

**Comment by zlepper** [comment]
> No matter how it gets there, I would be absolutely thrilled if rebus-org could incorporate an Rebus.OpenTelemetry repo at some point.
> 
> @zlepper if you build on @dariogriffo 's work somehow, maybe it makes sense to fork this repo and continue off of it? Then his commits will be there as a testament to groundwork made by him.
> 
> In any case, I'd be happy to accept the repo into rebus-org when it's ready for action 🤠 

I'll see what I can do.

Also now that I'm thinking about it, i assume Rebus has some test helpers and stuff for things like ingoing and outgoing behaviors? That means it's probably just as easy to test it outside :D

**Comment by mookid8000** [comment]
> Also now that I'm thinking about it, i assume Rebus has some test helpers and stuff for things like ingoing and outgoing behaviors? That means it's probably just as easy to test it outside :D

Not exactly sure I understand what you're saying here 😁 but if it's about testing calls to Open Telemetry APIs, it would be as simple as
```csharp
// intercept calls to Open Telemtry things with this
var interceptor = new FakeOpenTelemetryThing();

services.AddRebus(configure => configure
	.Transport(t => t.UseInMemoryTransport(network, queueName))
	.Options(o => {
		// intercept calls to something real in here
		o.Decorate<IOpenTelemetryThing>(c => interceptor);
	})
);
```
to intercept calls made to `IOpenTelemetryThing`, assuming that that's where the real Open Telemetry APIs are hiding.

**Comment by zlepper** [comment]
> > Also now that I'm thinking about it, i assume Rebus has some test helpers and stuff for things like ingoing and outgoing behaviors? That means it's probably just as easy to test it outside :D
> 
> Not exactly sure I understand what you're saying here 😁 but if it's about testing calls to Open Telemetry APIs, it would be as simple as
> 
> ```cs
> // intercept calls to Open Telemtry things with this
> var interceptor = new FakeOpenTelemetryThing();
> 
> services.AddRebus(configure => configure
> 	.Transport(t => t.UseInMemoryTransport(network, queueName))
> 	.Options(o => {
> 		// intercept calls to something real in here
> 		o.Decorate<IOpenTelemetryThing>(c => interceptor);
> 	})
> );
> ```
> 
> to intercept calls made to `IOpenTelemetryThing`, assuming that that's where the real Open Telemetry APIs are hiding.

That was exactly my entire point, it is super easy to test Rebus things :D

**Comment by zlepper** [comment]
@mookid8000 I have something here that seems to work, at least according to the tests: https://github.com/zlepper/Rebus.OpenTelemetry Probably still needs some code quality cleanup. 

I have split the project in 2 parts. A part for adding the diagnostic traces, since that is independent of OpenTelemetry, and a part for OpenTelemetry specifically (That entire line of code it required). 

Hows the process going forward for this?

**Comment by mookid8000** [comment]
> I have something here that seems to work, at least according to the tests: https://github.com/zlepper/Rebus.OpenTelemetry Probably still needs some code quality cleanup.
>
> I have split the project in 2 parts. A part for adding the diagnostic traces, since that is independent of OpenTelemetry, and a part for OpenTelemetry specifically (That entire line of code it required).

Cool – does that mean that other kinds of metrics sinks can be plugged in? And if so, which one(s)?

> Hows the process going forward for this?

I think you can simply go and transfer ownership of your repo to me, and then I'll transfer it to rebus-org

**Comment by zlepper** [comment]
> > I have something here that seems to work, at least according to the tests: https://github.com/zlepper/Rebus.OpenTelemetry Probably still needs some code quality cleanup.
> > I have split the project in 2 parts. A part for adding the diagnostic traces, since that is independent of OpenTelemetry, and a part for OpenTelemetry specifically (That entire line of code it required).
> 
> Cool – does that mean that other kinds of metrics sinks can be plugged in? And if so, which one(s)?

Yes, that is at least the idea behind System.Diagnostics. Though it's so damn close to how OpenTelemetry is implemented, that i'm pretty sure that is going to be the only thing that actually hooks into it. 

If not, I imagine something like Datadog or equivalent can use them for hooking, if they don't just use OpenTelemetry directly also. 

>>Hows the process going forward for this?
>
> I think you can simply go and transfer ownership of your repo to me, and then I'll transfer it to rebus-org

I have requested a transfer for the repository now.

**Comment by mookid8000** [comment]
Excellent work!! It's out now as https://www.nuget.org/packages/Rebus.Diagnostics/ and https://www.nuget.org/packages/Rebus.OpenTelemetry/ 🎉 

Thanks for contributing – am looking forward to using this myself 🤠

**Comment by dariogriffo** [comment]
Excellent to know how this evolved :)
